exec-once = hyprctl setcursor Bibata-Modern-Classic 24
exec-once = waybar
exec-once = swww-daemon
exec-once = swaync
exec-once = pactl set-source-volume $(pactl get-default-source) 40%
exec-once = /usr/libexec/hyprpolkitagent
exec-once = udiskie
exec-once = openrgb --startminimized
