# Take me to your ruler

windowrule {
    name = suppress-maximize-events
    match:class = *
    suppress_event = maximize
}

windowrule {
    name = opaque-writedoc
    match:class = ^(kitty)$
    match:title = (writedoc)(.*)
    opaque = true
}

windowrule {
    name = make-youtube-opaque
    match:title = (.*)(YouTube)(.*)
    opaque = true
}

windowrule {
    name = make-cava-clear
    match:title = ^(cava)$
    no_blur = true
}

layerrule {
    name = make-swaync-layer-blur
    match:namespace = swaync-control-center
    blur = true
}
