font=JetBrainsMono-Regular:size=11
pad = 0x0

[cursor]
style=block
blink=yes

[colors-dark]
# Tokyo Night Color Scheme
alpha = 0
background=000000
foreground=c0caf5

## Normal colors
regular0=15161e  # Black
regular1=f7768e  # Red
regular2=9ece6a  # Green
regular3=e0af68  # Yellow
regular4=7aa2f7  # Blue
#regular5=bb9af7  # Magenta
regular5=9950ff  # Magenta
regular6=7dcfff  # Cyan
regular7=a9b1d6  # White

## Bright colors
bright0=414868   # Bright Black (Gray)
bright1=f7768e   # Bright Red
bright2=9ece6a   # Bright Green
bright3=e0af68   # Bright Yellow
bright4=7aa2f7   # Bright Blue
bright5=bb9af7   # Bright Magenta
bright6=7dcfff   # Bright Cyan
bright7=c0caf5   # Bright White

## Selection & Misc
selection-background=33467c
selection-foreground=c0caf5
urls=73daca
